#!/usr/bin/env python3
"""Regenerate every artifact in `examples/reports/` from `examples/sample_service/`.

⭐ WHY THIS IS A SCRIPT AND NOT A README INSTRUCTION.
The committed reports are the thing a prospect compares their own run against.
If they were produced by hand, they would drift from the tool on the first change
and the demo would quietly start proving the opposite of what it claims. So the
artifacts are generated by one command, and `tests/test_examples_reproduce.py`
asserts the committed ones still match what the tool produces today.

⚠️ `content_hash` is EXPECTED to differ on every run — it covers the issuance
timestamp. `findings_digest` is the value that reproduces, and it is the value the
test compares. Regenerating therefore produces a real diff in the timestamp lines,
which is correct and not a defect.

Usage:  python examples/regenerate.py
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TREE = "examples/sample_service"
OUT = "examples/reports"

STEPS: list[tuple[str, list[str]]] = [
    ("no-egress audit",   ["-m", "entrovouch.no_egress_auditor", TREE,
                           "--json", f"{OUT}/egress.json", "--md", f"{OUT}/egress.md",
                           "--label", "entrovouch/examples/sample_service"]),
    ("SARIF 2.1.0",       ["-m", "entrovouch.sarif", f"{OUT}/egress.json",
                           "--out", f"{OUT}/egress.sarif.json"]),
    ("in-toto Statement", ["-m", "entrovouch.attestation", f"{OUT}/egress.json",
                           "--out", f"{OUT}/egress.intoto.json"]),
    ("CBOM",              ["-m", "entrovouch.cbom", TREE,
                           "--json", f"{OUT}/cbom.json", "--md", f"{OUT}/cbom.md"]),
    ("CycloneDX 1.6",     ["-m", "entrovouch.cyclonedx", f"{OUT}/cbom.json",
                           "--out", f"{OUT}/cbom.cdx.json"]),
    ("key provenance",    ["-m", "entrovouch.key_provenance", TREE,
                           "--json", f"{OUT}/key_provenance.json",
                           "--label", "entrovouch/examples/sample_service"]),
    ("SBOM",              ["-m", "entrovouch.sbom", TREE,
                           "--json", f"{OUT}/sbom.json",
                           "--cdx", f"{OUT}/sbom.cdx.json",
                           "--md", f"{OUT}/sbom.md",
                           "--label", "entrovouch/examples/sample_service"]),
]


def main() -> int:
    (REPO / OUT).mkdir(parents=True, exist_ok=True)
    failed = []
    for label, args in STEPS:
        r = subprocess.run([sys.executable, *args], cwd=REPO, capture_output=True,
                           text=True, encoding="utf-8", errors="replace")
        # ⚡ EXIT 1 IS NOT AN ERROR HERE. The scanners follow the usual convention:
        # 0 = clean, 1 = findings, 2 = could not run. The fixture is built to
        # PRODUCE findings, so treating 1 as failure would have made the demo
        # report failure for working correctly. (The first version of this script
        # did exactly that, and the fixture proved it wrong within a minute.)
        ok = r.returncode in (0, 1)
        print(f"  {'ok  ' if ok else 'FAIL'} {label}  (exit {r.returncode})")
        if not ok:
            failed.append(label)
            print((r.stderr or r.stdout or "")[-500:])
    if failed:
        print(f"\n  FAILED: {failed}")
        return 1
    print("\n  All artifacts regenerated. `content_hash` and timestamps will differ;")
    print("  `findings_digest` must not. Run the test suite to confirm.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
